[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
show_error_codes = True
exclude = (?x)(
    ^LightAgent/
  | ^\.venv/
  )

[mypy-LightAgent.*]
ignore_missing_imports = True

[mypy-alembic.*]
ignore_missing_imports = True

[mypy-asyncpg.*]
ignore_missing_imports = True

[mypy-opentelemetry.*]
ignore_missing_imports = True

[mypy-pint.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True

[mypy-sympy.*]
ignore_missing_imports = True

[mypy-z3.*]
ignore_missing_imports = True
