"""Route C3 self-play material through the existing Corpus Factory, §S21C3-035 and §4.11.

Three kinds of material leave a campaign, and only two of them are corpus candidates:

* the *task package* — the issue description and the provider-visible source, which is the
  same text a provider would be shown. Self-play, generated by this system, Apache-2.0;
* the *correction examples* — the `ExperienceCandidate`s the Experience Compiler produced
  from the ordered correction paths. Also self-play;
* the *outcomes* — what actually happened in a container. Those are `REAL_GOVERNED_RUN`
  evidence and are evaluation-only; they go to learned intake and never come here. §4.11
  draws that line and this module does not have a function that would cross it.

Nothing here inspects or normalizes anything itself. `inspect_local_directory` already reads
a workspace safely and `inspect_experience_candidate` already refuses a candidate that is not
still `proposed`; re-implementing either would be a second opinion about safety, which is one
opinion too many. This module's whole job is to say what the material *is* — its rights, its
scope, and above all which group it belongs to, because that is what decides the split.

The group is the repository group. §4.12 requires every outcome and every parameter variant
of one task to stay in one split, and `CorpusFactoryRequest.split_group_key` is how the
factory is told which group this ingest belongs to. Leaving it unset would scatter the five
variants of a task across four splits and quietly leak the answer into the evaluation set.
"""

from __future__ import annotations

from pathlib import Path
from uuid import UUID, uuid5

from cognitive_os.config.corpus_config import CorpusConfiguration
from cognitive_os.corpus.sources import (
    InspectedSource,
    inspect_experience_candidate,
    inspect_local_directory,
)
from cognitive_os.domain.common import UtcDatetime
from cognitive_os.domain.corpus import (
    CorpusDestinationType,
    CorpusFactoryRequest,
    CorpusSourceType,
    CorpusUsageRight,
)
from cognitive_os.domain.experience import ExperienceCandidate
from cognitive_os.domain.memory import MemorySensitivity
from cognitive_os.domain.reality import RealityTaskManifest

#: Fixed forever: a re-ingested task package must be the same request, not a new one.
REALITY_CORPUS_NAMESPACE = UUID("8c4d20e6-3f71-5a98-b6e2-05d1c8734af9")

CORPUS_ACTOR = "reality-campaign"

#: What this system may do with material it generated itself. `MODEL_TRAINING` is true
#: because self-play task text is exactly the kind of thing a training corpus may hold —
#: and is still not permission to train, which corpus export cannot initiate in any case.
SELF_PLAY_RIGHTS: dict[CorpusUsageRight, bool | None] = {
    CorpusUsageRight.INTERNAL_USE: True,
    CorpusUsageRight.MODIFICATION: True,
    CorpusUsageRight.DERIVATIVE_WORK: True,
    CorpusUsageRight.BENCHMARK_USE: True,
    CorpusUsageRight.MODEL_TRAINING: True,
    CorpusUsageRight.REDISTRIBUTION: True,
    CorpusUsageRight.PUBLIC_RELEASE: True,
    CorpusUsageRight.COMMERCIAL_USE: True,
}


def task_package_source(
    task: RealityTaskManifest, *, workspace: Path, config: CorpusConfiguration
) -> InspectedSource:
    """Inspect the provider-visible workspace. The control bundle lives outside it.

    Reading the workspace rather than reconstructing the projection is deliberate: it is the
    same directory the sandbox mounted, so material that reached the corpus is material a
    provider could have seen, and there is no second rendering that could disagree.
    """
    return inspect_local_directory(
        workspace,
        source_identity=f"reality-task:{task.task_id}",
        source_revision=task.content_hash,
        config=config,
    )


def task_package_request(
    task: RealityTaskManifest, *, created_at: UtcDatetime
) -> CorpusFactoryRequest:
    return CorpusFactoryRequest(
        request_id=uuid5(REALITY_CORPUS_NAMESPACE, f"task:{task.task_id}"),
        source_type=CorpusSourceType.DOCUMENT,
        source_identity=f"reality-task:{task.task_id}",
        source_revision=task.content_hash,
        scope=f"project:cognitive-os:{task.repository_group}",
        sensitivity=MemorySensitivity.PUBLIC,
        license_identifiers=(task.rights.licence_identifier,),
        usage_rights=dict(SELF_PLAY_RIGHTS),
        requested_destination=CorpusDestinationType.TRAINING_CORPUS,
        split_group_key=task.repository_group,
        created_at=created_at,
        created_by=CORPUS_ACTOR,
    )


def correction_source(
    candidate: ExperienceCandidate, *, config: CorpusConfiguration
) -> InspectedSource:
    return inspect_experience_candidate(
        candidate, source_revision=candidate.content_hash, config=config
    )


def correction_request(
    candidate: ExperienceCandidate,
    *,
    task: RealityTaskManifest,
    created_at: UtcDatetime,
) -> CorpusFactoryRequest:
    """One curated correction example, kept in its task's group.

    The group is the *task's* repository group, not the candidate's identity. A correction
    written for a task is about that task; putting it anywhere else in the split would let an
    evaluation be scored against the fix for the very problem it is measuring.
    """
    return CorpusFactoryRequest(
        request_id=uuid5(REALITY_CORPUS_NAMESPACE, f"correction:{candidate.candidate_id}"),
        source_type=CorpusSourceType.EXPERIENCE_CANDIDATE,
        source_identity=f"experience-candidate:{candidate.candidate_id}",
        source_revision=candidate.content_hash,
        scope=f"project:cognitive-os:{task.repository_group}",
        sensitivity=MemorySensitivity.PUBLIC,
        license_identifiers=(task.rights.licence_identifier,),
        usage_rights=dict(SELF_PLAY_RIGHTS),
        requested_destination=CorpusDestinationType.TRAINING_CORPUS,
        split_group_key=task.repository_group,
        created_at=created_at,
        created_by=CORPUS_ACTOR,
    )
