"""The frozen query table for the retrieval benchmark, §S21C3-053.

Sixty queries, two per repair task, written as an operator would actually type them: from the
symptom they are looking at, not from the wording of the record they hope to find. That is the
whole reason this is a hand-written table rather than a slice of the task text.

A query generated by transforming a document is a string-matching exercise. Bag-of-words
retrieval would answer it perfectly, the deterministic hashing provider — which is a
bag-of-words model with a hash for a vocabulary — would answer it perfectly too, and §4.15's
requirement that MiniLM beat that provider by 0.15 absolute recall@5 would be unreachable for a
reason that says nothing about either model. So the overlap is kept low deliberately: the
queries say *falling back*, *trailing entries*, *ring*, *bucketing*, where the records say
*default*, *last n items*, *wrap around*, *group*.

These are frozen. They were written before any arm was run, and §4.15 is explicit that a failed
threshold is corrected in the benchmark or left open as a gate — never by rewording the
evaluation set until the number improves.

Each entry is `(template_id, kind, text)`. The kind decides which record is relevant, in
`reality_retrieval.py`; nothing here names a record, so relevance cannot be quietly retargeted
one query at a time.
"""

from __future__ import annotations

#: The five query shapes §S21C3-053 requires, each appearing twelve times across the table.
QUERY_KINDS: tuple[str, ...] = ("terminology", "symptom", "failure", "correction", "analogous")

QUERIES: tuple[tuple[str, str, str], ...] = (
    (
        "boundary_collections.first_match",
        "terminology",
        "utility that grabs the leading element out of a list with a fallback when nothing is "
        "there",
    ),
    (
        "boundary_collections.first_match",
        "failure",
        "why would a helper hand back nothing at all for a list that clearly has entries in it",
    ),
    (
        "boundary_collections.take_last",
        "symptom",
        "asking for none of the trailing entries gives me everything back",
    ),
    (
        "boundary_collections.take_last",
        "correction",
        "requesting zero trailing entries must yield an empty result and a count below zero must "
        "be turned away",
    ),
    (
        "boundary_collections.chunk",
        "failure",
        "the tail of my data disappears whenever the total does not divide evenly",
    ),
    (
        "boundary_collections.chunk",
        "analogous",
        "splitting a long list into fixed-width blocks without losing the remainder",
    ),
    (
        "boundary_collections.dedupe",
        "correction",
        "distinct entries must come back in the order they were first seen, zeros and blanks "
        "included",
    ),
    (
        "boundary_collections.dedupe",
        "terminology",
        "utility that strips repeats out of a list without reordering it",
    ),
    (
        "boundary_collections.window_pairs",
        "analogous",
        "walking a list two neighbours at a time",
    ),
    (
        "boundary_collections.window_pairs",
        "symptom",
        "the final entry gets matched with the leading one as though the data were a ring",
    ),
    (
        "parsing_validation.key_values",
        "terminology",
        "reader for settings written as name=value joined by commas",
    ),
    (
        "parsing_validation.key_values",
        "failure",
        "a trailing comma or an extra equals sign inside the value makes the reader blow up",
    ),
    (
        "parsing_validation.parse_bool",
        "symptom",
        "a misspelt flag in my settings file quietly turns the feature off instead of complaining",
    ),
    (
        "parsing_validation.parse_bool",
        "correction",
        "yes/no text should be read regardless of capitalisation and anything unrecognised must be "
        "reported",
    ),
    (
        "parsing_validation.split_fields",
        "failure",
        "one record ends up with more columns than the next because a separator sat inside quotes",
    ),
    (
        "parsing_validation.split_fields",
        "analogous",
        "cutting a single delimited line into columns while respecting quotes",
    ),
    (
        "parsing_validation.parse_version",
        "correction",
        "a release string with two components must be padded so it compares equal to the "
        "three-component form",
    ),
    (
        "parsing_validation.parse_version",
        "terminology",
        "turning dotted release numbers into something you can order",
    ),
    (
        "parsing_validation.normalize_header",
        "analogous",
        "canonicalising protocol field names before looking them up",
    ),
    (
        "parsing_validation.normalize_header",
        "symptom",
        "the same field spelled with underscores never matches the dashed spelling",
    ),
    (
        "state_idempotency.register",
        "terminology",
        "a small name-to-value table where registering twice is safe",
    ),
    (
        "state_idempotency.register",
        "failure",
        "restarting the service replaced a stored entry and reported it as brand new",
    ),
    (
        "state_idempotency.advance",
        "symptom",
        "a mistyped event does nothing at all and looks like it worked",
    ),
    (
        "state_idempotency.advance",
        "correction",
        "an unrecognised event, and a valid one arriving out of order, must both be reported "
        "loudly",
    ),
    (
        "state_idempotency.merge_settings",
        "failure",
        "layering overrides changed the original mapping for every later caller",
    ),
    (
        "state_idempotency.merge_settings",
        "analogous",
        "combining a defaults mapping with a caller's overrides",
    ),
    (
        "state_idempotency.acquire_slot",
        "correction",
        "a worker that comes back must land on the position it already had, and going over the "
        "limit must fail",
    ),
    (
        "state_idempotency.acquire_slot",
        "terminology",
        "handing out a bounded number of stable positions keyed by name",
    ),
    (
        "state_idempotency.checkpoint",
        "analogous",
        "keeping a short trail of recent progress markers",
    ),
    (
        "state_idempotency.checkpoint",
        "symptom",
        "retrying a step fills the trail with the same marker over and over and it never stops "
        "growing",
    ),
    ("numeric_logic.mean", "terminology", "arithmetic average helper"),
    ("numeric_logic.mean", "failure", "the average of one and two comes out as one"),
    (
        "numeric_logic.percentage",
        "symptom",
        "the report dies with a division error when the denominator is nothing",
    ),
    (
        "numeric_logic.percentage",
        "correction",
        "a share of nothing must be reported as an invalid argument, and the figure kept to two "
        "decimals",
    ),
    (
        "numeric_logic.clamp",
        "failure",
        "swapping the two limits by mistake leaves the number untouched instead of complaining",
    ),
    (
        "numeric_logic.clamp",
        "analogous",
        "pinning a number inside an inclusive lower and upper limit",
    ),
    (
        "numeric_logic.divide_evenly",
        "correction",
        "the pieces handed back must add up to exactly what was handed in",
    ),
    (
        "numeric_logic.divide_evenly",
        "terminology",
        "splitting an amount into whole-number shares",
    ),
    (
        "numeric_logic.compound",
        "analogous",
        "growing an amount over a whole number of periods",
    ),
    (
        "numeric_logic.compound",
        "symptom",
        "a negative period count quietly shrinks the amount instead of being refused",
    ),
    (
        "error_handling.lookup",
        "terminology",
        "fetching a value out of nested dictionaries with a dotted path",
    ),
    (
        "error_handling.lookup",
        "failure",
        "the log only names the missing segment, so I cannot tell which of eleven paths failed",
    ),
    (
        "error_handling.first_success",
        "symptom",
        "when every fallback fails I get an empty result that looks like a real answer",
    ),
    (
        "error_handling.first_success",
        "correction",
        "an empty chain must be refused and the last failure re-raised when nothing works",
    ),
    (
        "error_handling.parse_or_default",
        "failure",
        "passing None instead of text silently produced the fallback rather than reporting my bug",
    ),
    (
        "error_handling.parse_or_default",
        "analogous",
        "reading a whole-number setting with a fallback when the text is not one",
    ),
    (
        "error_handling.close_all",
        "correction",
        "shutdown must keep going past a failing resource and report how many were released",
    ),
    (
        "error_handling.close_all",
        "terminology",
        "releasing a set of open resources during shutdown",
    ),
    (
        "error_handling.require",
        "analogous",
        "checking a caller precondition and reporting it as a domain failure",
    ),
    (
        "error_handling.require",
        "symptom",
        "the failure arrives as an assertion, and vanishes entirely when the interpreter is "
        "optimised",
    ),
    ("data_transformation.group_by", "terminology", "bucketing rows by one field's value"),
    (
        "data_transformation.group_by",
        "failure",
        "the buckets come out alphabetically, which reorders every downstream report",
    ),
    (
        "data_transformation.invert",
        "symptom",
        "an integer identifier comes back as text after flipping the mapping around",
    ),
    (
        "data_transformation.invert",
        "correction",
        "flipping a mapping must preserve types and refuse when two entries share a value",
    ),
    (
        "data_transformation.rename_keys",
        "failure",
        "relabelling a projection also changed the stored record",
    ),
    (
        "data_transformation.rename_keys",
        "analogous",
        "changing the labels of a mapping's entries",
    ),
    (
        "data_transformation.to_records",
        "correction",
        "columns of unequal length must be refused rather than silently cut to the shortest",
    ),
    (
        "data_transformation.to_records",
        "terminology",
        "turning column-oriented data into one record per row",
    ),
    (
        "data_transformation.summarize",
        "analogous",
        "aggregating one numeric field over a set of rows",
    ),
    (
        "data_transformation.summarize",
        "symptom",
        "an empty result set crashes the aggregate with a division error",
    ),
)
