"""Deterministic generation of rights-clean repair tasks, §S21C3-020.

This module is the machinery. The corpus itself — thirty tasks across six families — is the
`TaskSpec` table in `reality_task_specs`, kept separate so that adding a family is a data
change and never a code change. A template that needed new machinery here would be a sign the
shape is wrong.

Three properties are load-bearing, and the generator enforces them rather than trusting a
convention:

*Byte-identical regeneration.* Every file is literal text keyed by a template and a seed.
Nothing is timestamped, nothing is uuid4-ed into content, and a task's identity is a uuid5
over the template and seed — so a task regenerated on another machine is the same task, and a
corpus that cannot be regenerated cannot be audited.

*The control bundle lives outside the workspace.* `write_task` puts visible files under
`<root>/workspace` and hidden tests under `<root>/control`, never nested. A hidden test written
into the workspace would be readable by the candidate, by any provider and by the repository
indexer, and it would still pass every test that only checks the mount is read-only.

*Every candidate replaces exactly the one file under repair.* `incomplete_a` and `incomplete_b`
rewrite the same function differently, which is why an adversary cannot concatenate the corpus
edits into a patch that solves everything: the two halves of the answer conflict on the same
lines. §S21C3-024 asserts that rather than assuming it.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from uuid import UUID, uuid5

from cognitive_os.domain.common import UtcDatetime
from cognitive_os.domain.memory import MemorySensitivity
from cognitive_os.domain.reality import (
    RealityCandidateStrategy,
    RealityContentEntry,
    RealitySourceRights,
    RealityTaskDifficulty,
    RealityTaskFamily,
    RealityTaskManifest,
    RealityTaskProjection,
)

from .reality_task_specs import TASK_SPECS, TaskSpec

#: Fixed forever: it is what makes a regenerated task the same task.
REALITY_TASK_NAMESPACE = UUID("6f2a1c94-8d3b-5e17-a4c0-2b9d7e5f83a1")

#: The project owns every generated byte, so the rights answer is the project's own licence.
#: It is still recorded per task and still `verified` by an operator input rather than
#: inferred, because ADR 0088 keeps redistribution separate from openness.
GENERATED_TASK_LICENCE = "Apache-2.0"

GENERATOR_PROFILE_ID = "reality.tasks"
GENERATOR_PROFILE_VERSION = 1

#: Shared by every control bundle. The hidden suite runs from `/verification` while the code
#: under repair is bind-mounted at `/workspace`; importing across that gap is all this does.
CONTROL_CONFTEST = '''"""Put the workspace under test on the import path.

The hidden suite lives at /verification and the code under repair is bind-mounted at
/workspace, read-write for the candidate and never for this suite.
"""

import sys

sys.path.insert(0, "/workspace/src")
'''

#: Written into the workspace so the *visible* suite can import the same module locally.
#: Kept out of `allowed_paths`, so a candidate that edits it is a file-policy violation.
VISIBLE_CONFTEST = '''"""Put the package under test on the import path."""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent / "src"))
'''

_ORDERED_STRATEGIES = (
    RealityCandidateStrategy.INCOMPLETE_A,
    RealityCandidateStrategy.CORRECT_NARROW,
    RealityCandidateStrategy.INCOMPLETE_B,
    RealityCandidateStrategy.CORRECT_ROBUST,
)


@dataclass(frozen=True, slots=True)
class TaskTemplate:
    """One repair task expanded into literal file contents."""

    template_id: str
    family: RealityTaskFamily
    repository_group: str
    difficulty: RealityTaskDifficulty
    issue_description: str
    expected_behavior: str
    baseline_failure_reason: str
    visible_files: dict[str, str]
    control_files: dict[str, str]
    candidate_sources: dict[RealityCandidateStrategy, dict[str, str]]


@dataclass(frozen=True, slots=True)
class GeneratedTask:
    """A task package on disk, plus the manifest that describes it."""

    manifest: RealityTaskManifest
    template: TaskTemplate
    workspace: Path
    control: Path

    def candidate_files(self, strategy: RealityCandidateStrategy) -> dict[str, str]:
        return self.template.candidate_sources[strategy]


def _digest(text: str) -> str:
    return sha256(text.encode()).hexdigest()


def _module_source(spec: TaskSpec, function_source: str) -> str:
    header = f'"""{spec.module_doc}"""\n'
    if spec.imports:
        header += f"\n{spec.imports}\n"
    return f"{header}\n\n{function_source.strip()}\n"


def _expand(spec: TaskSpec) -> TaskTemplate:
    source_path = f"src/{spec.module}.py"
    return TaskTemplate(
        template_id=spec.template_id,
        family=spec.family,
        repository_group=spec.repository_group,
        difficulty=spec.difficulty,
        issue_description=spec.issue,
        expected_behavior=spec.expected,
        baseline_failure_reason=spec.baseline_reason,
        visible_files={
            source_path: _module_source(spec, spec.baseline),
            f"tests/test_{spec.module}.py": spec.visible_test,
            "conftest.py": VISIBLE_CONFTEST,
        },
        control_files={
            "conftest.py": CONTROL_CONFTEST,
            f"test_hidden_{spec.module}.py": spec.hidden_test,
        },
        candidate_sources={
            RealityCandidateStrategy.INCOMPLETE_A: {
                source_path: _module_source(spec, spec.incomplete_a)
            },
            RealityCandidateStrategy.CORRECT_NARROW: {
                source_path: _module_source(spec, spec.correct_narrow)
            },
            RealityCandidateStrategy.INCOMPLETE_B: {
                source_path: _module_source(spec, spec.incomplete_b)
            },
            RealityCandidateStrategy.CORRECT_ROBUST: {
                source_path: _module_source(spec, spec.correct_robust)
            },
        },
    )


_TEMPLATES: dict[str, TaskTemplate] = {spec.template_id: _expand(spec) for spec in TASK_SPECS}


def available_templates() -> tuple[str, ...]:
    return tuple(sorted(_TEMPLATES))


def template(template_id: str) -> TaskTemplate:
    return _TEMPLATES[template_id]


def offline_strategies() -> tuple[RealityCandidateStrategy, ...]:
    """The four of §4.6, in the order a correction trajectory walks them."""
    return _ORDERED_STRATEGIES


def build_manifest(
    template_id: str,
    *,
    seed: int,
    hidden_bundle_artifact_id: UUID,
    hidden_bundle_hash: str,
    created_at: UtcDatetime,
) -> RealityTaskManifest:
    """Describe one task without writing anything.

    The manifest is built from the template's literal text, so the hashes it declares are the
    hashes of the bytes `write_task` will produce. Building it from files already on disk would
    make the manifest a description of whatever happened to be there.
    """
    item = _TEMPLATES[template_id]
    task_id = uuid5(REALITY_TASK_NAMESPACE, f"{template_id}:{seed}")
    projection = RealityTaskProjection(
        task_id=task_id,
        task_family=item.family,
        difficulty=item.difficulty,
        issue_description=item.issue_description,
        expected_behavior=item.expected_behavior,
        visible_test_command=("pytest", "-q", "tests"),
        allowed_paths=("src",),
        forbidden_paths=("tests", "conftest.py"),
        files=tuple(
            RealityContentEntry(path=path, size_bytes=len(text.encode()), file_hash=_digest(text))
            for path, text in sorted(item.visible_files.items())
        ),
    )
    return RealityTaskManifest(
        task_id=task_id,
        task_family=item.family,
        repository_group=item.repository_group,
        difficulty=item.difficulty,
        generator_profile_id=GENERATOR_PROFILE_ID,
        generator_profile_version=GENERATOR_PROFILE_VERSION,
        generation_seed=seed,
        projection=projection,
        base_repository_manifest_hash=_manifest_hash(item.visible_files),
        hidden_verifier_bundle_artifact_id=hidden_bundle_artifact_id,
        hidden_verifier_bundle_hash=hidden_bundle_hash,
        control_material_manifest_hash=_manifest_hash(item.control_files),
        baseline_failure_reason=item.baseline_failure_reason,
        required_verifier_ids=("coding.hidden_pytest", "coding.pytest"),
        rights=RealitySourceRights(
            source_identity=f"cognitive-os:generated:{template_id}",
            licence_identifier=GENERATED_TASK_LICENCE,
            rights_verified=True,
            rights_evidence_hash=_digest(f"project-owned generated task:{template_id}"),
            attribution="Cognitive OS project, generated task package",
            sensitivity=MemorySensitivity.PUBLIC,
        ),
        created_at=created_at,
    )


def write_task(
    template_id: str,
    *,
    root: Path,
    seed: int,
    hidden_bundle_artifact_id: UUID,
    hidden_bundle_hash: str,
    created_at: UtcDatetime,
) -> GeneratedTask:
    """Materialize one task package under `root`, workspace and control kept apart."""
    item = _TEMPLATES[template_id]
    workspace = root / "workspace"
    control = root / "control"
    _write_tree(workspace, item.visible_files)
    _write_tree(control, item.control_files)
    return GeneratedTask(
        manifest=build_manifest(
            template_id,
            seed=seed,
            hidden_bundle_artifact_id=hidden_bundle_artifact_id,
            hidden_bundle_hash=hidden_bundle_hash,
            created_at=created_at,
        ),
        template=item,
        workspace=workspace,
        control=control,
    )


def apply_candidate(
    task: GeneratedTask, strategy: RealityCandidateStrategy, *, workspace: Path
) -> None:
    """Write one candidate's files over a copy of the base workspace."""
    _write_tree(workspace, task.candidate_files(strategy), create=False)


def _write_tree(root: Path, files: dict[str, str], *, create: bool = True) -> None:
    if create:
        root.mkdir(parents=True, exist_ok=True)
    for path, text in sorted(files.items()):
        destination = root / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8")


def _manifest_hash(files: dict[str, str]) -> str:
    return sha256(
        "\n".join(f"{path} {_digest(text)}" for path, text in sorted(files.items())).encode()
    ).hexdigest()
