"""Deterministic generation of rights-clean repair tasks, §S21C3-020.

This module is the machinery. The corpus itself — thirty tasks across six families — is the
`TaskSpec` table in `reality_task_specs`, kept separate so that adding a family is a data
change and never a code change. A template that needed new machinery here would be a sign the
shape is wrong.

Three properties are load-bearing, and the generator enforces them rather than trusting a
convention:

*Byte-identical regeneration.* Every file is literal text keyed by a template and a seed.
Nothing is timestamped, nothing is uuid4-ed into content, and a task's identity is a uuid5
over the template and seed — so a task regenerated on another machine is the same task, and a
corpus that cannot be regenerated cannot be audited.

*The control bundle lives outside the workspace.* `write_task` puts visible files under
`<root>/workspace` and hidden tests under `<root>/control`, never nested. A hidden test written
into the workspace would be readable by the candidate, by any provider and by the repository
indexer, and it would still pass every test that only checks the mount is read-only.

*Every candidate replaces exactly the one file under repair.* `incomplete_a` and `incomplete_b`
rewrite the same function differently, which is why an adversary cannot concatenate the corpus
edits into a patch that solves everything: the two halves of the answer conflict on the same
lines. §S21C3-024 asserts that rather than assuming it.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
from pathlib import Path
from uuid import UUID, uuid5

from cognitive_os.domain.common import UtcDatetime
from cognitive_os.domain.memory import MemorySensitivity
from cognitive_os.domain.reality import (
    D2_NEUTRAL_RECIPES,
    RealityCandidateStrategy,
    RealityContentEntry,
    RealitySourceRights,
    RealityTaskDifficulty,
    RealityTaskFamily,
    RealityTaskManifest,
    RealityTaskProjection,
)

from .reality_fixture_spec_d4 import D4_FIXTURE_SPEC
from .reality_fixture_spec_d5 import D5_FIXTURE_SPEC
from .reality_retrieval_specs_d3 import D3_RETRIEVAL_SPECS, D3RetrievalSpec
from .reality_retrieval_specs_d4 import D4_RETRIEVAL_SPECS
from .reality_retrieval_specs_d5 import D5_RETRIEVAL_SPECS
from .reality_task_specs import TASK_SPECS, TaskSpec
from .reality_task_specs_d2 import (
    D2_TASK_SPECS,
    INHERITED_VARIANT_FIELDS,
    D2TaskSpec,
    candidate_sources_for,
    recipe_binding,
)
from .reality_task_specs_d2 import module_source as d2_module_source
from .reality_task_specs_d3 import D3_TASK_SPECS
from .reality_task_specs_d4 import D4_CALIBRATION_SPECS
from .reality_task_specs_d5 import D5_CALIBRATION_SPECS
from .reality_task_specs_d6 import D6_CERTIFICATION_SPECS
from .reality_task_specs_d7 import D7_CERTIFICATION_SPECS
from .reality_task_specs_d7_final import D7_FINAL_REPLACEMENT_SPECS

#: Fixed forever: it is what makes a regenerated task the same task.
REALITY_TASK_NAMESPACE = UUID("6f2a1c94-8d3b-5e17-a4c0-2b9d7e5f83a1")

#: The project owns every generated byte, so the rights answer is the project's own licence.
#: It is still recorded per task and still `verified` by an operator input rather than
#: inferred, because ADR 0088 keeps redistribution separate from openness.
GENERATED_TASK_LICENCE = "Apache-2.0"

GENERATOR_PROFILE_ID = "reality.tasks"
GENERATOR_PROFILE_VERSION = 1

#: Shared by every control bundle. The hidden suite runs from `/verification` while the code
#: under repair is bind-mounted at `/workspace`; importing across that gap is all this does.
CONTROL_CONFTEST = '''"""Put the workspace under test on the import path.

The hidden suite lives at /verification and the code under repair is bind-mounted at
/workspace, read-write for the candidate and never for this suite.
"""

import sys

sys.path.insert(0, "/workspace/src")
'''

#: Written into the workspace so the *visible* suite can import the same module locally.
#: Kept out of `allowed_paths`, so a candidate that edits it is a file-policy violation.
VISIBLE_CONFTEST = '''"""Put the package under test on the import path."""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent / "src"))
'''

_ORDERED_STRATEGIES = (
    RealityCandidateStrategy.INCOMPLETE_A,
    RealityCandidateStrategy.CORRECT_NARROW,
    RealityCandidateStrategy.INCOMPLETE_B,
    RealityCandidateStrategy.CORRECT_ROBUST,
)


@dataclass(frozen=True, slots=True)
class TaskTemplate:
    """One repair task expanded into literal file contents."""

    template_id: str
    family: RealityTaskFamily
    repository_group: str
    difficulty: RealityTaskDifficulty
    issue_description: str
    expected_behavior: str
    baseline_failure_reason: str
    visible_files: dict[str, str]
    control_files: dict[str, str]
    candidate_sources: dict[RealityCandidateStrategy, dict[str, str]]
    #: The same four bodies keyed by the D2 neutral recipes. A C3 template carries both
    #: keyings because thirty C3 groups are inherited into D2's training partition, and
    #: running one of them under `correct_narrow` would carry the label oracle in with it.
    #: For a D2 template the two mappings are the same object: it has no other keying.
    neutral_candidate_sources: dict[RealityCandidateStrategy, dict[str, str]]

    def sources(self, strategy: RealityCandidateStrategy) -> dict[str, str]:
        """The files one candidate writes, under whichever naming the caller used."""
        if strategy in D2_NEUTRAL_RECIPES:
            return self.neutral_candidate_sources[strategy]
        return self.candidate_sources[strategy]


@dataclass(frozen=True, slots=True)
class GeneratedTask:
    """A task package on disk, plus the manifest that describes it."""

    manifest: RealityTaskManifest
    template: TaskTemplate
    workspace: Path
    control: Path

    def candidate_files(self, strategy: RealityCandidateStrategy) -> dict[str, str]:
        return self.template.sources(strategy)


def _digest(text: str) -> str:
    return sha256(text.encode()).hexdigest()


def _module_source(spec: TaskSpec, function_source: str) -> str:
    header = f'"""{spec.module_doc}"""\n'
    if spec.imports:
        header += f"\n{spec.imports}\n"
    return f"{header}\n\n{function_source.strip()}\n"


def _expand(spec: TaskSpec) -> TaskTemplate:
    source_path = f"src/{spec.module}.py"
    return TaskTemplate(
        template_id=spec.template_id,
        family=spec.family,
        repository_group=spec.repository_group,
        difficulty=spec.difficulty,
        issue_description=spec.issue,
        expected_behavior=spec.expected,
        baseline_failure_reason=spec.baseline_reason,
        visible_files={
            source_path: _module_source(spec, spec.baseline),
            f"tests/test_{spec.module}.py": spec.visible_test,
            "conftest.py": VISIBLE_CONFTEST,
        },
        control_files={
            "conftest.py": CONTROL_CONFTEST,
            f"test_hidden_{spec.module}.py": spec.hidden_test,
        },
        candidate_sources={
            RealityCandidateStrategy.INCOMPLETE_A: {
                source_path: _module_source(spec, spec.incomplete_a)
            },
            RealityCandidateStrategy.CORRECT_NARROW: {
                source_path: _module_source(spec, spec.correct_narrow)
            },
            RealityCandidateStrategy.INCOMPLETE_B: {
                source_path: _module_source(spec, spec.incomplete_b)
            },
            RealityCandidateStrategy.CORRECT_ROBUST: {
                source_path: _module_source(spec, spec.correct_robust)
            },
        },
        neutral_candidate_sources={
            recipe: {source_path: _module_source(spec, getattr(spec, field))}
            for recipe, field in zip(
                recipe_binding(spec.template_id), INHERITED_VARIANT_FIELDS, strict=True
            )
        },
    )


def _expand_d2(spec: D2TaskSpec) -> TaskTemplate:
    """One D2 spec as a template, with its variants placed under the neutral recipes.

    The only difference from `_expand` is where the candidate bodies come from. C3 names its
    four by correctness; D2 authors four variants and `candidate_sources_for` applies the
    per-task recipe binding, so the recipe a candidate carries says nothing about its label.
    Everything else — the file layout, both conftests, the hidden bundle — is identical,
    because a D2 task has to be measurable by exactly the machinery C3's was.
    """
    source_path = f"src/{spec.module}.py"
    return TaskTemplate(
        template_id=spec.template_id,
        family=spec.family,
        repository_group=spec.repository_group,
        difficulty=spec.difficulty,
        issue_description=spec.issue,
        expected_behavior=spec.expected,
        baseline_failure_reason=spec.baseline_reason,
        visible_files={
            source_path: d2_module_source(spec, spec.baseline),
            f"tests/test_{spec.module}.py": spec.visible_test,
            "conftest.py": VISIBLE_CONFTEST,
        },
        control_files={
            "conftest.py": CONTROL_CONFTEST,
            f"test_hidden_{spec.module}.py": spec.hidden_test,
        },
        candidate_sources=(neutral := candidate_sources_for(spec, source_path)),
        neutral_candidate_sources=neutral,
    )


def _expand_retrieval(spec: D3RetrievalSpec) -> TaskTemplate:
    """One retrieval source group as a task package: the failed state and its accepted repair.

    Two bodies rather than four, because a retrieval group is evidence for one graph pair and
    not a four-way ranking decision. The package layout, both conftests and the hidden bundle
    are the correction corpus's, so the same runner records it and the same verifier decides
    it — a retrieval pair is a *causal* claim only if the same machinery says so.
    """
    source_path = f"src/{spec.module}.py"
    repair = {
        RealityCandidateStrategy.CORRECT_NARROW: {source_path: spec.module_text(spec.repaired)}
    }
    return TaskTemplate(
        template_id=spec.template_id,
        family=spec.family,
        repository_group=spec.repository_group,
        difficulty=RealityTaskDifficulty.SINGLE_EDIT,
        issue_description=spec.issue,
        expected_behavior=spec.expected,
        baseline_failure_reason=spec.failure_reason,
        visible_files={
            source_path: spec.module_text(spec.failed),
            f"tests/test_{spec.module}.py": spec.visible_test,
            "conftest.py": VISIBLE_CONFTEST,
        },
        control_files={
            "conftest.py": CONTROL_CONFTEST,
            f"test_hidden_{spec.module}.py": spec.hidden_test,
        },
        candidate_sources=repair,
        neutral_candidate_sources=repair,
    )


_TEMPLATES: dict[str, TaskTemplate] = {spec.template_id: _expand(spec) for spec in TASK_SPECS}

_D2_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_d2(spec) for spec in D2_TASK_SPECS
}

#: D3's twenty fresh calibration groups plus its vertical-slice fixture. A D3 spec *is* a D2
#: spec — four variants under the same neutral recipe binding — so it expands through exactly
#: the same path and needs no third expander.
_D3_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_d2(spec) for spec in D3_TASK_SPECS
}

#: D3's sixty retrieval source groups. Separate from `_D3_TEMPLATES` because they are a
#: different role with a different shape: two bodies, evaluation only, and no place in any
#: correction catalogue. `d3_templates()` must not grow by sixty groups no partition selected.
_D3_RETRIEVAL_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_retrieval(spec) for spec in D3_RETRIEVAL_SPECS
}

#: D4's hundred fresh calibration groups plus its vertical-slice fixture. The fixture comes
#: from a sibling module because `reality_task_specs_d4.py` was hashed into
#: `evidence/sprint-21d4-corpus.json` before S21D4-033 authored it; here is where the two
#: belong together, since the registry addresses a task by ID and not by source file.
_D4_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_d2(spec) for spec in (*D4_CALIBRATION_SPECS, D4_FIXTURE_SPEC)
}

#: D4's sixty retrieval source groups, on D3's retrieval shape and through D3's expander,
#: because they are D3 retrieval specs — the same two-body, evaluation-only role.
_D4_RETRIEVAL_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_retrieval(spec) for spec in D4_RETRIEVAL_SPECS
}

#: D5's hundred fresh calibration groups plus its vertical-slice fixture. Same D2 shape and the
#: same expander again. The fixture comes from a sibling module because `reality_task_specs_d5.py`
#: was hashed into the corpus, separation and seal records before S21D5-024 authored it; here is
#: where the two belong together, since the registry addresses a task by ID and not by source
#: file.
_D5_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_d2(spec) for spec in (*D5_CALIBRATION_SPECS, D5_FIXTURE_SPEC)
}

#: D5's sixty retrieval source groups, on the same two-body evaluation-only shape as D3's.
_D5_RETRIEVAL_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_retrieval(spec) for spec in D5_RETRIEVAL_SPECS
}

#: D6's fresh certification groups. Same D2 shape and the same expander: the registry addresses
#: a task by ID, and a ninth registry would only mean a ninth thing for the runner to know about.
_D6_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_d2(spec) for spec in D6_CERTIFICATION_SPECS
}

#: D7's fresh certification groups, on the same D2 shape and through the same expander.
_D7_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_d2(spec) for spec in D7_CERTIFICATION_SPECS
}

#: The four replacements S21D7-038 authorised for the two carried final roles. A separate
#: registry from the certification one because they belong to different roles and a reader
#: should not have to work out which of the hundred-and-four is which.
_D7_FINAL_TEMPLATES: dict[str, TaskTemplate] = {
    spec.template_id: _expand_d2(spec) for spec in D7_FINAL_REPLACEMENT_SPECS
}

#: Every corpus under one lookup, because the runner, the candidate builder and the retrieval
#: plane address a task by ID and should not have to know which sprint authored it. The nine
#: are still separate registries above: `available_templates()` is C3's campaign surface and
#: must not silently grow by six hundred and ninety-seven tasks.
_ALL_TEMPLATES: dict[str, TaskTemplate] = {
    **_TEMPLATES,
    **_D2_TEMPLATES,
    **_D3_TEMPLATES,
    **_D3_RETRIEVAL_TEMPLATES,
    **_D4_TEMPLATES,
    **_D4_RETRIEVAL_TEMPLATES,
    **_D5_TEMPLATES,
    **_D5_RETRIEVAL_TEMPLATES,
    **_D6_TEMPLATES,
    **_D7_TEMPLATES,
    **_D7_FINAL_TEMPLATES,
}

_REGISTERED = (
    len(_TEMPLATES)
    + len(_D2_TEMPLATES)
    + len(_D3_TEMPLATES)
    + len(_D3_RETRIEVAL_TEMPLATES)
    + len(_D4_TEMPLATES)
    + len(_D4_RETRIEVAL_TEMPLATES)
    + len(_D5_TEMPLATES)
    + len(_D5_RETRIEVAL_TEMPLATES)
    + len(_D6_TEMPLATES)
    + len(_D7_TEMPLATES)
    + len(_D7_FINAL_TEMPLATES)
)
if len(_ALL_TEMPLATES) != _REGISTERED:  # pragma: no cover - import guard
    raise RuntimeError(
        "a template ID collides across two corpora; merging the registries would drop a task "
        "silently and give one repository group two different bodies"
    )


def available_templates() -> tuple[str, ...]:
    """C3's corpus. Unchanged by D2: it is what the C3 campaign and its integrity check run."""
    return tuple(sorted(_TEMPLATES))


def d2_templates() -> tuple[str, ...]:
    """D2's corpus. Named separately so a caller has to say which corpus it means."""
    return tuple(sorted(_D2_TEMPLATES))


def d3_templates() -> tuple[str, ...]:
    """D3's corpus, fixture included. The catalogue selects the twenty it scores."""
    return tuple(sorted(_D3_TEMPLATES))


def d3_retrieval_templates() -> tuple[str, ...]:
    """D3's retrieval source pool. Evaluation only: no correction role ever selects one."""
    return tuple(sorted(_D3_RETRIEVAL_TEMPLATES))


def d4_templates() -> tuple[str, ...]:
    """D4's corpus, fixture included. The catalogue selects the hundred it scores."""
    return tuple(sorted(_D4_TEMPLATES))


def d4_retrieval_templates() -> tuple[str, ...]:
    """D4's retrieval source pool. Evaluation only: no correction role ever selects one."""
    return tuple(sorted(_D4_RETRIEVAL_TEMPLATES))


def d5_templates() -> tuple[str, ...]:
    """D5's corpus. The catalogue selects the hundred it scores."""
    return tuple(sorted(_D5_TEMPLATES))


def d5_retrieval_templates() -> tuple[str, ...]:
    """D5's retrieval source pool. Evaluation only: no correction role ever selects one."""
    return tuple(sorted(_D5_RETRIEVAL_TEMPLATES))


def template(template_id: str) -> TaskTemplate:
    return _ALL_TEMPLATES[template_id]


def offline_strategies() -> tuple[RealityCandidateStrategy, ...]:
    """The four of §4.6, in the order a correction trajectory walks them."""
    return _ORDERED_STRATEGIES


def build_manifest(
    template_id: str,
    *,
    seed: int,
    hidden_bundle_artifact_id: UUID,
    hidden_bundle_hash: str,
    created_at: UtcDatetime,
) -> RealityTaskManifest:
    """Describe one task without writing anything.

    The manifest is built from the template's literal text, so the hashes it declares are the
    hashes of the bytes `write_task` will produce. Building it from files already on disk would
    make the manifest a description of whatever happened to be there.
    """
    item = _ALL_TEMPLATES[template_id]
    task_id = uuid5(REALITY_TASK_NAMESPACE, f"{template_id}:{seed}")
    projection = RealityTaskProjection(
        task_id=task_id,
        task_family=item.family,
        difficulty=item.difficulty,
        issue_description=item.issue_description,
        expected_behavior=item.expected_behavior,
        visible_test_command=("pytest", "-q", "tests"),
        allowed_paths=("src",),
        forbidden_paths=("tests", "conftest.py"),
        files=tuple(
            RealityContentEntry(path=path, size_bytes=len(text.encode()), file_hash=_digest(text))
            for path, text in sorted(item.visible_files.items())
        ),
    )
    return RealityTaskManifest(
        task_id=task_id,
        task_family=item.family,
        repository_group=item.repository_group,
        difficulty=item.difficulty,
        generator_profile_id=GENERATOR_PROFILE_ID,
        generator_profile_version=GENERATOR_PROFILE_VERSION,
        generation_seed=seed,
        projection=projection,
        base_repository_manifest_hash=_manifest_hash(item.visible_files),
        hidden_verifier_bundle_artifact_id=hidden_bundle_artifact_id,
        hidden_verifier_bundle_hash=hidden_bundle_hash,
        control_material_manifest_hash=_manifest_hash(item.control_files),
        baseline_failure_reason=item.baseline_failure_reason,
        required_verifier_ids=("coding.hidden_pytest", "coding.pytest"),
        rights=RealitySourceRights(
            source_identity=f"cognitive-os:generated:{template_id}",
            licence_identifier=GENERATED_TASK_LICENCE,
            rights_verified=True,
            rights_evidence_hash=_digest(f"project-owned generated task:{template_id}"),
            attribution="Cognitive OS project, generated task package",
            sensitivity=MemorySensitivity.PUBLIC,
        ),
        created_at=created_at,
    )


def write_task(
    template_id: str,
    *,
    root: Path,
    seed: int,
    hidden_bundle_artifact_id: UUID,
    hidden_bundle_hash: str,
    created_at: UtcDatetime,
) -> GeneratedTask:
    """Materialize one task package under `root`, workspace and control kept apart."""
    item = _ALL_TEMPLATES[template_id]
    workspace = root / "workspace"
    control = root / "control"
    _write_tree(workspace, item.visible_files)
    _write_tree(control, item.control_files)
    return GeneratedTask(
        manifest=build_manifest(
            template_id,
            seed=seed,
            hidden_bundle_artifact_id=hidden_bundle_artifact_id,
            hidden_bundle_hash=hidden_bundle_hash,
            created_at=created_at,
        ),
        template=item,
        workspace=workspace,
        control=control,
    )


def apply_candidate(
    task: GeneratedTask, strategy: RealityCandidateStrategy, *, workspace: Path
) -> None:
    """Write one candidate's files over a copy of the base workspace."""
    _write_tree(workspace, task.candidate_files(strategy), create=False)


def _write_tree(root: Path, files: dict[str, str], *, create: bool = True) -> None:
    if create:
        root.mkdir(parents=True, exist_ok=True)
    for path, text in sorted(files.items()):
        destination = root / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(text, encoding="utf-8")


def _manifest_hash(files: dict[str, str]) -> str:
    return sha256(
        "\n".join(f"{path} {_digest(text)}" for path, text in sorted(files.items())).encode()
    ).hexdigest()
