"""Persistence boundary for model capabilities and routing evidence."""

from typing import Protocol
from uuid import UUID

from cognitive_os.domain.routing import (
    ModelCapabilityProfile,
    RoutingAccessRecord,
    RoutingDecision,
    RoutingExperiment,
    RoutingObservation,
    RoutingOutcome,
    RoutingPolicyRevision,
    RoutingStatistics,
)


class CapabilityRepositoryPort(Protocol):
    async def register_profile(self, profile: ModelCapabilityProfile) -> None: ...
    async def get_profile(
        self, model_identity_hash: str, revision: int | None = None
    ) -> ModelCapabilityProfile | None: ...
    async def query_profiles(self, *, limit: int = 256) -> tuple[ModelCapabilityProfile, ...]: ...
    async def create_policy(self, policy: RoutingPolicyRevision) -> None: ...
    async def get_policy(
        self, policy_id: str, revision: int | None = None
    ) -> RoutingPolicyRevision | None: ...
    async def record_observation(self, observation: RoutingObservation) -> None: ...
    async def list_observations(self, *, limit: int = 10_000) -> tuple[RoutingObservation, ...]: ...
    async def record_decision(self, decision: RoutingDecision) -> None: ...
    async def record_outcome(self, outcome: RoutingOutcome) -> None: ...
    async def record_statistics(self, statistics: RoutingStatistics) -> None: ...
    async def list_statistics(self, *, limit: int = 100_000) -> tuple[RoutingStatistics, ...]: ...
    async def record_experiment(self, experiment: RoutingExperiment) -> None: ...
    async def record_access(self, access: RoutingAccessRecord) -> None: ...


class RoutingReaderPort(Protocol):
    decisions: dict[UUID, RoutingDecision]
    observations: dict[UUID, RoutingObservation]
