"""Persistence boundary for append-only Corpus Factory state."""

from typing import Protocol
from uuid import UUID

from cognitive_os.domain.corpus import (
    CorpusAccessRecord,
    CorpusClassification,
    CorpusExportManifest,
    CorpusItem,
    CorpusManifest,
    CorpusRouteDecision,
    CorpusStatusTransition,
    SourceManifest,
)


class CorpusRepositoryPort(Protocol):
    async def register_source(self, source: SourceManifest) -> None: ...
    async def get_source(self, source_manifest_id: UUID) -> SourceManifest | None: ...
    async def get_source_by_identity(
        self, identity: str, revision: str
    ) -> SourceManifest | None: ...
    async def create_item(self, item: CorpusItem) -> None: ...
    async def get_item(self, corpus_item_id: UUID) -> CorpusItem | None: ...
    async def query_by_content_hash(
        self, content_hash: str, *, limit: int = 100
    ) -> tuple[CorpusItem, ...]: ...
    async def link_item_source(self, corpus_item_id: UUID, source_manifest_id: UUID) -> None: ...
    async def record_classification(self, classification: CorpusClassification) -> None: ...
    async def record_route_decision(self, decision: CorpusRouteDecision) -> None: ...
    async def advance_item_status(self, transition: CorpusStatusTransition) -> CorpusItem: ...
    async def create_manifest(self, manifest: CorpusManifest) -> None: ...
    async def get_manifest(self, corpus_id: UUID, revision: int) -> CorpusManifest | None: ...
    async def create_export(self, export: CorpusExportManifest) -> None: ...
    async def record_access(self, records: tuple[CorpusAccessRecord, ...]) -> None: ...
