"""Application boundary for deterministic experience compilation."""

from typing import Protocol
from uuid import UUID

from cognitive_os.domain.experience import ExperienceCompilationRequest
from cognitive_os.experience.compiler import ExperienceCompilationResult


class ExperienceCompilerPort(Protocol):
    def prepare_compilation(self, request: ExperienceCompilationRequest) -> None: ...
    def compile(self, request: ExperienceCompilationRequest) -> ExperienceCompilationResult: ...
    def resume_compilation(
        self, request: ExperienceCompilationRequest
    ) -> ExperienceCompilationResult: ...
    def cancel_compilation(self, compilation_id: UUID) -> None: ...
    def read_compilation(self, compilation_id: UUID) -> ExperienceCompilationResult | None: ...
    def validate_manifest(self, result: ExperienceCompilationResult) -> bool: ...
