"""Sandbox application boundary."""

from typing import Protocol

from cognitive_os.domain.sandbox import SandboxRequest, SandboxResult


class SandboxPort(Protocol):
    async def run(self, request: SandboxRequest) -> SandboxResult: ...
    async def cancel(self, sandbox_id: str) -> None: ...
    async def inspect(self, sandbox_id: str) -> dict[str, object]: ...
    async def cleanup(self, sandbox_id: str) -> None: ...
    async def list_stale(self) -> tuple[str, ...]: ...
