"""Persistence-neutral semantic-memory repository boundary."""

from typing import Protocol
from uuid import UUID

from cognitive_os.domain.semantic_memory import (
    Claim,
    ClaimRelation,
    ClaimRevision,
    ContradictionRecord,
    ContradictionRevision,
    EvidenceLink,
    SemanticAccessRecord,
    SemanticObservation,
    SemanticQueryResult,
    TemporalClaimQuery,
    WikiPage,
    WikiPageRevision,
)


class SemanticMemoryRepositoryPort(Protocol):
    async def record_observation(self, observation: SemanticObservation) -> SemanticObservation: ...
    async def get_observation(self, observation_id: UUID) -> SemanticObservation | None: ...
    async def list_observations(
        self, *, source_id: UUID | None = None, limit: int = 100
    ) -> tuple[SemanticObservation, ...]: ...
    async def create_claim(
        self, claim: Claim, revision: ClaimRevision
    ) -> tuple[Claim, ClaimRevision]: ...
    async def create_claim_with_evidence(
        self, claim: Claim, revision: ClaimRevision, evidence: tuple[EvidenceLink, ...]
    ) -> tuple[Claim, ClaimRevision]: ...
    async def append_claim_revision(
        self, revision: ClaimRevision, *, expected_revision: int
    ) -> ClaimRevision: ...
    async def append_claim_revision_with_evidence(
        self,
        revision: ClaimRevision,
        evidence: tuple[EvidenceLink, ...],
        *,
        expected_revision: int,
    ) -> ClaimRevision: ...
    async def get_claim(self, claim_id: UUID) -> Claim | None: ...
    async def get_claim_revision(self, claim_id: UUID, revision: int) -> ClaimRevision | None: ...
    async def list_claim_history(
        self, claim_id: UUID, *, limit: int = 100
    ) -> tuple[ClaimRevision, ...]: ...
    async def attach_evidence(self, evidence: EvidenceLink) -> EvidenceLink: ...
    async def list_evidence(
        self, claim_id: UUID, *, revision: int | None = None
    ) -> tuple[EvidenceLink, ...]: ...
    async def add_claim_relation(self, relation: ClaimRelation) -> ClaimRelation: ...
    async def list_claim_relations(self, claim_id: UUID) -> tuple[ClaimRelation, ...]: ...
    async def create_contradiction(
        self, contradiction: ContradictionRecord, revision: ContradictionRevision
    ) -> tuple[ContradictionRecord, ContradictionRevision]: ...
    async def get_contradiction(self, contradiction_id: UUID) -> ContradictionRecord | None: ...
    async def get_contradiction_revision(
        self, contradiction_id: UUID, revision: int
    ) -> ContradictionRevision | None: ...
    async def list_contradictions(self) -> tuple[ContradictionRecord, ...]: ...
    async def list_contradiction_history(
        self, contradiction_id: UUID
    ) -> tuple[ContradictionRevision, ...]: ...
    async def append_contradiction_revision(
        self, revision: ContradictionRevision, *, expected_revision: int
    ) -> ContradictionRevision: ...
    async def query_claims(self, query: TemporalClaimQuery) -> SemanticQueryResult: ...
    async def record_semantic_access(self, records: tuple[SemanticAccessRecord, ...]) -> None: ...
    async def create_wiki_page(self, page: WikiPage) -> WikiPage: ...
    async def get_wiki_page(self, page_id: UUID) -> WikiPage | None: ...
    async def get_wiki_revision(self, page_id: UUID, revision: int) -> WikiPageRevision | None: ...
    async def list_wiki_history(self, page_id: UUID) -> tuple[WikiPageRevision, ...]: ...
    async def append_wiki_revision(
        self, revision: WikiPageRevision, *, expected_revision: int
    ) -> WikiPageRevision: ...
