"""Persistence-neutral boundary for governed procedural skills."""

from typing import Protocol
from uuid import UUID

from cognitive_os.domain.skills import (
    SkillAccessRecord,
    SkillExecutionResult,
    SkillItem,
    SkillRevision,
    SkillStatistics,
)


class SkillRepositoryPort(Protocol):
    async def create_skill(self, item: SkillItem, revision: SkillRevision) -> SkillItem: ...
    async def append_revision(
        self, revision: SkillRevision, *, expected_revision: int
    ) -> SkillRevision: ...
    async def get_current(self, skill_id: UUID) -> tuple[SkillItem, SkillRevision] | None: ...
    async def get_revision(self, skill_id: UUID, revision: int) -> SkillRevision | None: ...
    async def list_revisions(
        self, skill_id: UUID, *, limit: int = 100
    ) -> tuple[SkillRevision, ...]: ...
    async def query_candidates(
        self, *, limit: int = 200
    ) -> tuple[tuple[SkillItem, SkillRevision], ...]: ...
    async def record_execution(self, result: SkillExecutionResult) -> SkillExecutionResult: ...
    async def get_execution(self, execution_id: UUID) -> SkillExecutionResult | None: ...
    async def list_executions(
        self, skill_id: UUID, revision: int
    ) -> tuple[SkillExecutionResult, ...]: ...
    async def record_access(self, records: tuple[SkillAccessRecord, ...]) -> None: ...
    async def list_accesses(
        self, skill_id: UUID, revision: int, *, limit: int = 200
    ) -> tuple[SkillAccessRecord, ...]: ...
    async def read_statistics(self, skill_id: UUID, revision: int) -> SkillStatistics | None: ...
    async def write_statistics(self, statistics: SkillStatistics) -> None: ...
