"""Existing-controller execution boundary for exact skill revisions."""

from typing import Protocol
from uuid import UUID

from cognitive_os.domain.skills import SkillExecutionRequest, SkillExecutionResult


class SkillExecutorPort(Protocol):
    async def prepare_execution(self, request: SkillExecutionRequest) -> SkillExecutionRequest: ...
    async def start_execution(self, request: SkillExecutionRequest) -> SkillExecutionResult: ...
    async def resume_execution(self, execution_id: UUID) -> SkillExecutionResult: ...
    async def cancel_execution(self, execution_id: UUID, reason: str) -> SkillExecutionResult: ...
    async def read_execution(self, execution_id: UUID) -> SkillExecutionResult | None: ...
