"""Infrastructure-neutral verifier application ports."""

from typing import Protocol

from cognitive_os.domain.problems import CriterionType, ProblemDomain
from cognitive_os.domain.verification import VerifierResult
from cognitive_os.domain.verifiers import (
    VerificationRequest,
    VerificationSubjectType,
    VerifierDescriptor,
    VerifierHealth,
    VerifierKind,
)


class VerifierPort(Protocol):
    @property
    def descriptor(self) -> VerifierDescriptor: ...

    async def verify(self, request: VerificationRequest) -> VerifierResult: ...

    async def health_check(self) -> VerifierHealth: ...


class VerifierRegistryPort(Protocol):
    def register(self, verifier: VerifierPort) -> None: ...
    def register_many(self, verifiers: tuple[VerifierPort, ...]) -> None: ...
    def get(self, verifier_id: str, version: str) -> VerifierPort | None: ...
    def require(self, verifier_id: str, version: str) -> VerifierPort: ...
    def list_all(self) -> tuple[VerifierDescriptor, ...]: ...
    def list_available(self) -> tuple[VerifierDescriptor, ...]: ...
    def list_by_kind(self, kind: VerifierKind) -> tuple[VerifierDescriptor, ...]: ...
    def list_by_domain(self, domain: ProblemDomain) -> tuple[VerifierDescriptor, ...]: ...
    def list_capable(
        self,
        subject_type: VerificationSubjectType,
        domain: ProblemDomain,
        criterion_type: CriterionType,
    ) -> tuple[VerifierDescriptor, ...]: ...
    def freeze(self) -> None: ...
    def snapshot(self) -> str: ...
