"""Persistence boundary for weakness mining and diagnostic queue state."""

from typing import Protocol
from uuid import UUID

from cognitive_os.domain.weakness import (
    ImpactScore,
    MiningRequest,
    MiningRunManifest,
    MiningRunStatus,
    MiningSourceSnapshot,
    WeaknessAccessRecord,
    WeaknessClusterSnapshot,
    WeaknessEvidencePackage,
    WeaknessGroupSnapshot,
    WeaknessIdentity,
    WeaknessQueueEntry,
    WeaknessQueueSnapshot,
    WeaknessRevision,
    WeaknessSignal,
)


class WeaknessRepositoryPort(Protocol):
    async def create_mining_run(self, request: MiningRequest) -> MiningRequest: ...
    async def get_mining_run_by_idempotency_key(self, key: str) -> MiningRequest | None: ...
    async def set_mining_status(self, run_id: UUID, status: MiningRunStatus) -> None: ...
    async def record_source_snapshot(self, snapshot: MiningSourceSnapshot) -> None: ...
    async def record_signals(self, signals: tuple[WeaknessSignal, ...]) -> None: ...
    async def list_signals(self, *, limit: int = 100_000) -> tuple[WeaknessSignal, ...]: ...
    async def record_group_snapshot(self, snapshot: WeaknessGroupSnapshot) -> None: ...
    async def record_cluster_snapshot(self, snapshot: WeaknessClusterSnapshot) -> None: ...
    async def create_weakness(
        self, identity: WeaknessIdentity, revision: WeaknessRevision
    ) -> None: ...
    async def append_weakness_revision(
        self, revision: WeaknessRevision, *, expected_revision: int
    ) -> None: ...
    async def get_weakness_revision(
        self, weakness_id: UUID, revision: int | None = None
    ) -> WeaknessRevision | None: ...
    async def record_impact_score(self, score: ImpactScore) -> None: ...
    async def record_evidence_package(self, package: WeaknessEvidencePackage) -> None: ...
    async def record_queue_entry(self, entry: WeaknessQueueEntry) -> None: ...
    async def record_queue_snapshot(self, snapshot: WeaknessQueueSnapshot) -> None: ...
    async def record_manifest(self, manifest: MiningRunManifest) -> None: ...
    async def record_access(self, access: WeaknessAccessRecord) -> None: ...
